- src/services/EdFi.DataManagementService.Api/Configuration/AppSettings.cs
- src/services/EdFi.DataManagementService.Api/Infrastructure/LogAppSettingsService.cs
- src/services/EdFi.DataManagementService.Api/Infrastructure/WebApplicationBuilderExtensions.cs
- src/services/EdFi.DataManagementService.Api/Program.cs
- src/services/EdFi.DataManagementService.Api/appsettings.json
Added LogAppSettingsService for enabling the IOptions pattern to do dependency injection on AppSettings. "LogAppSettingsService" may be refactored to work with logging.
> [DMS-9] Pre-wire for appSettings

- src/Dockerfile
The Dockerfile tried to use ASPNETCORE_HTTP_PORT env var, which does not work right now as some web pages have claimed.
With further investigation, it seems that this needs to be pluralized, as shown in this output:
```
docker run -it -e ASPNETCORE_HTTP_PORTS=93 local/edfi-data-management-service:latest .
2024-03-18 14:22:30.223 INF Now listening on: http://[::]:93
2024-03-18 14:22:30.249 INF Application started. Press Ctrl+C to shut down.
2024-03-18 14:22:30.250 INF Hosting environment: Production
2024-03-18 14:22:30.250 INF Content root path: /app
```
> [DMS-44] Pluralized Env name

- .gitignore
- docs/RUNNING-LOCALLY.md
- src/backend/EdFi.DataManagementService.Backend.Postgresql.Test.Integration/Configuration.cs
- src/backend/EdFi.DataManagementService.Backend.Postgresql.Test.Integration/EdFi.DataManagementService.Backend.Postgresql.Test.Integration.csproj
As per the team's conclusion. 
1.  Added a provision to include appsettings.Test.json in the integration tests project, if needed.
2.  The appsettings.Development.json file has been removed from the AspNetCore project.
3.  The RUNNING-LOCALLY.md document has been updated with the relevant details.
> [DMS-229] Developer settings for running app and/or integration tests

- eng/docker-compose/README.md
- src/tests/EdFi.DataManagementService.Tests.E2E/Features/ResourceQueries/PagingQueryString.feature
- src/tests/EdFi.DataManagementService.Tests.E2E/README.md
`GET` requests with paging and offset parameters were previously failing. Unable to reproduce. Some documentation updates in this pull request, and re-enable ignored tests but otherwise no material changes.
> [DMS-363] Paging tests failing

- .github/workflows/on-prerelease.yml
Updated all uses of slsa-github-generator to use tag `v2.0.0` instead of branch `main`
> [DEVOPS-136] Replace main version to v2.0.0

- eng/docker-compose/start-local-dms.ps1
- src/dms/core/EdFi.DataManagementService.Core/Middleware/ParsePathMiddleware.cs
For the quotation --> apostrophe, I'm tired of seeing this:
I should look for other places we have quotation marks in error messages and fix those too. At another time.
> PowerShell fix and apostrophes

- src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/AspNetCoreFrontend.cs
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/General/URLValidation.feature
Adds support for mixed case query params.
E.g. `/ed-fi/schools?liMIt=2`  becomes acceptable with the applied changes.
The original solutionwas to evaluate the toLower cases of each of the params from within the Context.FrontendRequest object. This resulted in performing the correct validation for the values, but validation failed downstream with 400 even after parsing.
This solution performs a check for the reserve params `totalCount`, `limit`, and `offset` by intercepting the query params and writing the correct form prior to creating the FrontendRequest object. This allows the validation to still occur while leaving the original HTTP Request Context intact.
> [DMS-397] Case insensitive limit, offset, totalCount params.

- src/config/backend/EdFi.DmsConfigurationService.Backend.Keycloak/KeycloakClientRepository.cs
- src/config/backend/EdFi.DmsConfigurationService.Backend.Keycloak/KeycloakServiceExtensions.cs
- src/config/backend/EdFi.DmsConfigurationService.Backend.Keycloak/KeycloakSettings.cs
- src/config/backend/EdFi.DmsConfigurationService.Backend.Keycloak/KeycloakTokenManager.cs
- src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Configuration/AppSettings.cs
- src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Configuration/IdentitySettings.cs
- src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Infrastructure/WebApplicationBuilderExtensions.cs
- src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Program.cs
- src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/appsettings.json
- Separated keycloak specific settings from broader identity settings 
- Introduced `IdentityProvider` app setting for future use (currently only support Keycloak)
- Moved keycloak service configuration to the keycloak backend project
- More settings validation
> [DMS-387] Refactor application startup for future support of alternate IdP

- eng/docker-compose/kafka-elasticsearch-ui.yml
- eng/docker-compose/kafka-elasticsearch.yml
- src/config/.config/dotnet-tools.json
- src/dms/.config/dotnet-tools.json
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Management/OpenSearchContainerSetup.cs
Before running the E2E tests (recommended to delete the docker-compose container, associated volumes and images): 
`.\start-local-dms.ps1 -EnvironmentFile ./.env.e2e -EnableSearchEngineUI -SearchEngine "ElasticSearch" -r`
- No changes are needed in `.env.e2e` file.
> [DMS-437] E2E testing for Elasticsearch

- .github/workflows/scheduled-build.yml
Fixing breaking changes after update to v2.0.0
Parameter 'channel-id' is no longer valid on v2.0.0 (must be configured in slack's webhook)
> [DMS-516] Update parameters for slack notification

- src/config/Dockerfile
- src/config/Nuget.Dockerfile
- src/dms/Dockerfile
- src/dms/Nuget.Dockerfile
- Updated gradle base image to allow docker to pull the image based on the host architecture
- Fixed Hadolint DL3022 following https://github.com/hadolint/hadolint/issues/830
> [DMS-520] Support arm64 dev environments

- src/config/backend/EdFi.DmsConfigurationService.Backend.Postgresql/Deploy/Scripts/0005_Insert_ClaimSet_NamespaceBased_Auth.sql
- src/config/backend/EdFi.DmsConfigurationService.Backend.Postgresql/Deploy/Scripts/0005_Insert_ClaimSet_SisVendor.sql
- src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateDocumentMiddlewareTests.cs
- src/dms/core/EdFi.DataManagementService.Core/Validation/DocumentValidator.cs
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsOnly.feature
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Resources/CreateResourcesValidation.feature
The reason for this change is because the bulkLoader is sending to DMS arrays with an empty object, e.g.` “gradeLevels”: [{}]`
> [DMS-541] DMS errors on optional array types

- eng/docker-compose/opensearch_connector.json
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Deploy/Scripts/0101_Create_EducationOrganizationHierarchy_Triggers.sql
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsOnly.feature
After trying several unsuccessful ways to transform the values to int64 (transformations in postgresql_connector.json and using a custom SMT), I ended up validating the option to store the EducationOrganizationId values as Text in the Hierarchy field of the EducationOrganizationHierarchyTermsLookup table and that's what worked.
In my local environment all the e2e tests passed (using OpenSearch and ElasticSearch).
Steps to test:
1. run one of this command:
For Opensearch
./start-local-dms.ps1 -EnvironmentFile "./.env.e2e" -SearchEngine "OpenSearch" -EnableConfig -r -EnableSearchEngineUI
or for ElasticSearch
./start-local-dms.ps1 -EnvironmentFile "./.env.e2e" -SearchEngine "ElasticSearch" -EnableConfig -r -EnableSearchEngineUI
2. .\setup-keycloak.ps1
3. Execute E2E test from VS.
> [DMS-556] Kafka transform failing on Hierarchy with mixed INT and BIGINT 

- .github/workflows/on-release.yml
Added jobs to retag pre release images; an execution test can be seen [here](https://github.com/simpat-jesus/Data-Management-Service/actions/runs/14092042309/job/39470828720)
Pre release images are not removed from docker hub.
> [DMS-564] Fix docker image tags on release

- src/dms/Nuget.Dockerfile
This additional copy logic here overwrites some of the libraries in the core dms and causes runtime errors
> [DMS-593] Fix School Year Data Load in Published Docker Image

- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/PostgresqlAuthorizationRepository.cs
- src/dms/core/EdFi.DataManagementService.Core.External/Interface/IAuthorizationRepository.cs
- src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Security/AuthorizationValidation/RelationshipsWithEdOrgsAndPeopleValidatorTests.cs
- src/dms/core/EdFi.DataManagementService.Core/DmsCoreServiceExtensions.cs
- src/dms/core/EdFi.DataManagementService.Core/Security/AuthorizationFilters/RelationshipsFiltersProvider.cs
- src/dms/core/EdFi.DataManagementService.Core/Security/AuthorizationFilters/RelationshipsWithEdOrgsOnlyFiltersProvider.cs
- src/dms/core/EdFi.DataManagementService.Core/Security/AuthorizationFilters/RelationshipsWithStudentsOnlyFiltersProvider.cs
- src/dms/core/EdFi.DataManagementService.Core/Security/AuthorizationValidation/RelationshipsBasedAuthorizationHelper.cs
- src/dms/core/EdFi.DataManagementService.Core/Security/AuthorizationValidation/RelationshipsWithEdOrgsAndPeopleValidator.cs
- src/dms/core/EdFi.DataManagementService.Core/Security/AuthorizationValidation/RelationshipsWithStudentsOnlyValidator.cs
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsAndStudents.feature
- src/dms/tests/RestClient/test.studentContactAssociation.http
E2E tests will be covered by https://edfi.atlassian.net/browse/DMS-620.
Added tests with EdFiSAndbox claim set on test.studentContactAssociation.http file.
> [DMS-616] Contact Authorization: Contact-securable Document GET by ID/DELETE in DMS Core

- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/ContactStudentSchoolAuthorizationTests.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/DatabaseIntegrationTestHelper.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Deploy/Scripts/0103_Create_StudentSchoolAssociationAuthorization_Triggers.sql
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Deploy/Scripts/1001_Create_ContactStudentSchoolAuthorization_Table.sql
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsAndContacts.feature
Why the issue happened:
```
School                                  
│                                     
▼                                     
StudentSchoolAssociationAuthorization ─┐               
│                     │               
▼                     │               
StudentSchoolAssociation ──────┤ Cascade delete
│                     │               
▼                     │               
Student                 │               
│                     │               
▼                     │               
ContactStudentSchoolAuthorization ─┘               
│                                     
▼                                     
StudentContactAssociation                      
│                                     
▼                                     
Contact …
```
> [DMS-709] Grant access to Contacts after their StudentSchoolAssociation is recreated

- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Extensions/SampleExtension.feature
Tests were failing because property names are case insensitive. See [DMS-716](https://edfi.atlassian.net/browse/DMS-716)
[DMS-716]: https://edfi.atlassian.net/browse/DMS-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DMS-696] Data Validation with Staff when petName has leading or trailing spaces 

- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/Configuration.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/DatabaseIntegrationTestHelper.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/DatabaseTest.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/DatabaseTestBase.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/DeleteTests.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/EducationOrganizationHierarchyTests.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/GetTests.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/QueryTests.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/UpdateTests.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql.Tests.Integration/UpsertTests.cs
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Deploy/Scripts/0103_Create_StudentSchoolAssociationAuthorization_Triggers.sql
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Deploy/Scripts/0104_Create_EducationOrganizationHierarchyStudentSchoolAuthorization_Triggers.sql
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Deploy/Scripts/1007_Create_StaffEducationOrganizationAuthorization_Triggers.sql
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Deploy/Scripts/1008_Create_EducationOrganizationHierarchyStaffEdOrgAuthorization_Triggers.sql
- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/PostgresqlAuthorizationRepository.cs
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsAndContacts.feature
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsAndPeople.feature
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsAndStaffs.feature
Jsonb columns holding simple arrays cannot mix int32 and int64, no matter the sort order or else kafka will error and the data will not make it to opensearch. The fix here is to make them arrays of strings always.
> [DMS-706] LONG edOrgId support in kafka

- src/dms/core/EdFi.DataManagementService.Core/DmsCoreServiceExtensions.cs
- src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/Infrastructure/WebApplicationBuilderExtensions.cs
- src/dms/frontend/EdFi.DataManagementService.Frontend.SchoolYearLoader/HostBuilderExtensions.cs
Polly is logging response messages, including successful ones. For reads (GET/QUERY) these responses will have EdFiDoc. The change here will use the existing app config setting `maskRequestBodyInLogs` to redact the body when set. 
Sample logs here:
```
INF Execution attempt. Source: 'backendResiliencePipeline/(null)/Retry', Operation Key: 'null', Result: 'QuerySuccess { EdfiDocs = [
2025-06-04 14:56:35   "[REDACTED]"
2025-06-04 14:56:35 ], TotalCount = 1 }', Handled: 'False', Attempt: '0', Execution Time: 992.7237ms
2025-06-04 14:56:12 2025-06-04 19:56:12.243 INF Execution attempt. Source: 'backendResiliencePipeline/(null)/Retry', Operation Key: 'null', Result: 'GetSuccess { DocumentUuid = DocumentUuid { Value = 715b17a3-455c-4d9b-93b5-2ff96b7d94af }, EdfiDoc = [REDACTED], …
```
> [DMS-90] Redact EDFiDocs from polly logs

- eng/docker-compose/keycloak.yml
- Keycloak console log level up to Error
- The log level is the same in the container creation process.
After running all the e2e test the log console remains the same.
> [DMS-710] Fix Keycloak throwing many warnings per second

- eng/docker-compose/kafka-elasticsearch.yml
- eng/docker-compose/kafka-opensearch.yml
Verified these are the correct environment variables for each search engine by running `start-local-dms` with each and searching `dms-search` logs for `geoip`.
> [DMS-717] Disable geoip downloading in search

- src/dms/backend/EdFi.DataManagementService.Backend.Postgresql/Operation/SqlAction.cs
When using PostgreSQL as the QueryHandler, this failed when the TotalCount overflowed the int16.
> [DMS-758] Use int32 instead of int16 for the TotalCount result

- .github/workflows/Pkg EdFi.DmsApi.Sdk.yml
- .github/workflows/Pkg EdFi.DmsApi.TestSdk.yml
- build-sdk.ps1
- eng/sdkGen/EdFi.DmsApi.Sdk.nuspec
- eng/sdkGen/EdFi.DmsApi.TestSdk.nuspec
[dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.OdsApi.Sdk.Standard.5.2.0/overview/0.5.1-alpha.0.42](https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.OdsApi.Sdk.Standard.5.2.0/overview/0.5.1-alpha.0.42)
https://dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_artifacts/feed/EdFi/NuGet/EdFi.OdsApi.TestSdk.Standard.5.2.0/overview/0.5.1-alpha.0.42
> [DMS-766] Handle the Sdk namespace as a parameter in SmokeTest Utility for DMS SDK

- eng/docker-compose/.env.e2e
- eng/docker-compose/.env.example
- eng/docker-compose/README.md
- src/Directory.Packages.props
- src/dms/clis/EdFi.DataManagementService.ApiSchemaDownloader.Tests.Integration/ApiSchemaDownloaderTests.cs
- src/dms/clis/EdFi.DataManagementService.ApiSchemaDownloader/Properties/launchSettings.json
- src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/ResourceQueries/DescriptorQueriesQueryString.feature
Package update fixes missing `effectiveBegindate` and `effictaveEndDate` query fields on descriptors. E2E test verifies.
> [DMS-768] Missing query fields on descriptors 

- .github/workflows/scheduled-build.yml
- .github/workflows/scheduled-pre-image-test.yml
I compared the execution of the e2e from the PR and found that there is a step that the host performs. `run: echo "127.0.0.1 dms-kafka1" | sudo tee -a /etc/hosts` and with this change, the process is successfully completed.
> [DMS-820] Scheduled Jobs Fail
