.github/workflows/on-pullrequest-dockerfile.yml

- Add hadolint
- Add docker scout cves 
- Scan scout results to fail action if critical errors are found

[DMS-20] Run linting and docker scout for Dockerfile

---

.gitignore
build.ps1
eng/build-helpers.psm1

Replace Write-Host method with a new fuction that allows text color as parameter

[DMS-126] Update PowerShell Scripts to Avoid Write-Host

---

.github/workflows/after-pullrequest.yml
.github/workflows/on-merge-or-tag.yml
.github/workflows/on-prerelease.yml
.github/workflows/on-pullrequest-dockerfile.yml
.github/workflows/on-pullrequest.yml
.github/workflows/on-release.yml

Enhance job-level permissions within the workflow.
- after-pullrequest.yml
- on-merge-or-tag.yml
- on-prerelease.yml
- on-pullrequest-dockerfile.yml
- workflows/on-pullrequest.yml
- on-release.yml

[DMS-121] Improve Workflow Permissions

---

src/services/EdFi.DataManagementService.Api.Tests.E2E/Features/SchoolYearValidation.feature

DMS-116 School Year Validation
DMS-102 Abstract Entity Validation

[DMS-138] School Year Feature File

---

.github/dependabot.yml

Rename target branch dependabot file

[DMS-161] Rename target branch dependabot file

---

.github/workflows/after-pullrequest.yml

Add a top level "read all" permission in after-pullrequest.yml so that it matches all of the other action yml files.

[DMS-177] Added read all permision top level after-pullrequest

---

build.ps1

Rename and replace function name.

[DMS-134] Rename PowerShell Function

---

src/EdFi.DataManagementService.sln
src/backend/EdFi.DataManagementService.Backend.Installer/EdFi.DataManagementService.Backend.Installer.csproj
src/backend/EdFi.DataManagementService.Backend.Installer/Program.cs
src/backend/EdFi.DataManagementService.Backend.Installer/Properties/launchSettings.json

Right-click EdFi.DataManagementService.Backend.Installer properties -> debug
under debug -> general-> command line arguments
postgresql
host=localhost;port=5432;username=postgres;database=EdFi.DataManagementService;

[DMS-173] Database console installer

---

src/services/EdFi.DataManagementService.Api.Tests.E2E/Features/Resources/CreateResourcesValidation.feature.disabled
src/services/EdFi.DataManagementService.Api.Tests.E2E/Features/Resources/DeleteResourcesValidation.feature.disabled
src/services/EdFi.DataManagementService.Api.Tests.E2E/Features/Resources/ReadResourcesValidation.feature.disabled
src/services/EdFi.DataManagementService.Api.Tests.E2E/Features/Resources/UpdateResourcesValidation.feature.disabled

Adding resource operations for:
- CREATE
- READ
- UPDATE
- DELETE
Scenarios should work with any endpoints under Descriptors, currently there were designed with `absenceEventCategoryDescriptors`

[DMS-145] Adding Resource CRUD Operations

---

src/services/EdFi.DataManagementService.Api.Tests.E2E/Features/DescriptorReferenceValidation.feature.disabled

Addition of DescriptorReferenceValidation.feature.disabled file indicating 4 scenarios

[DMS-106] - DescriptorReferenceValidation

---

src/tests/EdFi.DataManagementService.Tests.E2E/Features/SubclassResourcesValidation.feature.disabled

Creation of SubclassResourcesValidation file with its scenario

[DMS-211] - Creation of SubclassResourcesValidation file with its scenario

---

src/tests/EdFi.DataManagementService.Tests.E2E/Features/InvalidReferenceValidation.feature.disabled

Creation of the file InvalidReferenceValidation.feature.disabled.
Keep working on the first scenario because of unexpected response

[DMS-212] - Creation of the Scenarios of InvalidReferenceValidation

---

src/tests/EdFi.DataManagementService.Tests.E2E/Features/InvalidReferenceValidation.feature.disabled

Fix of the first scenario related to StudentEducationOrganizationAssociation

[DMS-212] - InvalidReferenceValidation

---

.github/workflows/scheduled-build.yml

Scheduled Build Test and result on Slack

[DMS-227] Scheduled "PR" build and improved notification

---

build.ps1
docs/RUNNING-LOCALLY.md
src/backend/EdFi.DataManagementService.Backend.Mssql/EdFi.DataManagementService.Backend.Mssql.csproj
src/backend/EdFi.DataManagementService.Backend.Postgresql/EdFi.DataManagementService.Backend.Postgresql.csproj
src/core/EdFi.DataManagementService.Core.External/EdFi.DataManagementService.Core.External.csproj

- Exclude projects from the code coverage report
- Add documention about code coverage and how to generate the report
- Set the Threshold value to 55 since the minimun value is 58

[DMS-228] Refinement code coverage

---

.github/workflows/on-release.yml

Adding missing permission on-release

[DMS-256] Adding missing permission on-release

---

src/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateDocumentMiddlewareTests.cs
src/core/EdFi.DataManagementService.Core/Validation/DocumentValidator.cs
src/tests/EdFi.DataManagementService.Tests.E2E/Features/Resources/CreateResourcesValidation.feature
src/tests/EdFi.DataManagementService.Tests.E2E/Features/Resources/UpdateResourcesValidation.feature

- DocumentValidator
- Test Unit for ValidateDocumentMiddleware
- E2E Test for POST and PUT

[DMS-242] Overposting crashes

---

.github/workflows/on-release.yml
package-helpers.psm1

After the automated release promotion failed, I reviewed what we have working in AdminApi and adjusted here. I tested the release promotion script manually from my computer. This screenshot shows that it worked:

[DMS-264] Update to match the successful code from Admin API

---

.github/workflows/scheduled-build.yml
src/Directory.Packages.props
src/frontend/EdFi.DataManagementService.Frontend.AspNetCore/Modules/CoreEndpointModule.cs

See Slack for evidence that this is working. Even the error reports in Slack are useful: they show the "failure reporting" when I had temporarily introduced a build error. The only problem with those was the lack of the detailed error message.

[DMS-278] Improve scheduled build

---

src/backend/EdFi.DataManagementService.Backend.Postgresql.Test.Integration/DeleteTests.cs
src/backend/EdFi.DataManagementService.Backend.Postgresql.Test.Integration/UpdateTests.cs
src/backend/EdFi.DataManagementService.Backend.Postgresql.Test.Integration/UpsertTests.cs
src/backend/EdFi.DataManagementService.Backend.Postgresql/Operation/UpsertDocument.cs

Unable to reproduce the Serialization exceptions mentioned in the ticket, however fixed one scenario.

[DMS-296] Integration test failures

---

src/tests/EdFi.DataManagementService.Tests.E2E/Features/General/DiscoveryAPI.feature

[DMS-248-Fix] - Fix on Discovery API feature file

---

src/Directory.Packages.props
src/backend/EdFi.DataManagementService.Backend.OpenSearch/QueryOpenSearch.cs
src/core/EdFi.DataManagementService.Core.External/Backend/IQueryRequest.cs
src/core/EdFi.DataManagementService.Core.External/Model/JsonPath.cs
src/core/EdFi.DataManagementService.Core.External/Model/QueryElement.cs
src/core/EdFi.DataManagementService.Core.Tests.Unit/ApiSchemaBuilder.cs
src/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateEqualityConstraintMiddlewareTests.cs
src/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateQueryMiddlewareTests.cs
src/core/EdFi.DataManagementService.Core/ApiSchema/ApiSchema_Schema.json
src/core/EdFi.DataManagementService.Core/ApiSchema/Model/JsonPathAndType.cs
src/core/EdFi.DataManagementService.Core/ApiSchema/Model/QueryField.cs
src/core/EdFi.DataManagementService.Core/ApiSchema/ResourceSchema.cs
src/core/EdFi.DataManagementService.Core/Backend/QueryRequest.cs
src/core/EdFi.DataManagementService.Core/Middleware/ValidateQueryMiddleware.cs
src/core/EdFi.DataManagementService.Core/Model/QueryElementAndType.cs
src/core/EdFi.DataManagementService.Core/Pipeline/PipelineContext.cs
src/tests/EdFi.DataManagementService.Tests.E2E/Features/Descriptors/CreateDescriptorsValidation.feature
src/tests/EdFi.DataManagementService.Tests.E2E/Features/Descriptors/ReadDescriptorsValidation.feature
src/tests/EdFi.DataManagementService.Tests.E2E/Features/General/DiscoveryAPI.feature
src/tests/EdFi.DataManagementService.Tests.E2E/Features/ResourceQueries/ResourceQueriesQueryString.feature
src/tests/EdFi.DataManagementService.Tests.E2E/Features/ResourceQueries/TotalCountQueryString.feature
src/tests/EdFi.DataManagementService.Tests.E2E/Features/Resources/UpdateResourcesValidation.feature

I also activated some E2E tests targeting finished tickets.

[DMS-364] Validate query parameter value type

---

src/config/backend/EdFi.DmsConfigurationService.Backend.Keycloak/ClientRepository.cs
src/config/backend/EdFi.DmsConfigurationService.Backend.Keycloak/TokenManager.cs
src/config/backend/EdFi.DmsConfigurationService.Backend/ITokenManager.cs
src/config/backend/EdFi.DmsConfigurationService.Backend/KeycloakError.cs
src/config/backend/EdFi.DmsConfigurationService.Backend/Repositories/IClientRepository.cs
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore.Tests.Unit/Middleware/RequestLoggingMiddlewareTests.cs
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore.Tests.Unit/Modules/IdentityModuleTests.cs
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Infrastructure/KeycloakException.cs
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Middleware/RequestLoggingMiddleware.cs
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Model/RegisterRequest.cs
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Modules/ApplicationModule.cs
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Modules/IdentityModule.cs

Refactor `KeycloakError` and `KeycloakException`

Keycloak exception

---

docs/CONFIGURATION.md
src/Directory.Packages.props
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/EdFi.DmsConfigurationService.Frontend.AspNetCore.csproj
src/config/frontend/EdFi.DmsConfigurationService.Frontend.AspNetCore/Infrastructure/WebApplicationBuilderExtensions.cs
src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/EdFi.DataManagementService.Frontend.AspNetCore.csproj
src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/Infrastructure/WebApplicationBuilderExtensions.cs

Add support for environment variables and update documentation.

[DMS-458] Support environment variables

---

.vscode/settings.json
eng/docker-compose/.env.e2e
eng/docker-compose/.env.example
eng/docker-compose/kafka-elasticsearch-ui.yml
eng/docker-compose/kafka-elasticsearch.yml
eng/docker-compose/kafka-opensearch-ui.yml
eng/docker-compose/kafka-opensearch.yml
eng/docker-compose/keycloak.yml
eng/docker-compose/local-config.yml
eng/docker-compose/local-dms.yml
eng/docker-compose/postgresql.yml
eng/docker-compose/published-config.yml
eng/docker-compose/published-dms.yml
eng/docker-compose/start-local-config.ps1
eng/docker-compose/start-local-dms.ps1
eng/docker-compose/start-published-dms.ps1
eng/docker-compose/verify_services_are_running.http

I had to run the PR action manually, since there were no C# changes to trigger it.
* [Config Service PR workflow](https://github.com/Ed-Fi-Alliance-OSS/Data-Management-Service/actions/runs/14316990890)
* [DMS PR workflow](https://github.com/Ed-Fi-Alliance-OSS/Data-Management-Service/actions/runs/14317168591)

[DMS-612] Docker Compose Optimization

---

src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Authorization/RelationshipsWithEdOrgsAndStaffs.feature
src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Extensions/SampleExtension.feature
src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/Resources/CreateResourcesValidation.feature

4 defects created 
https://edfi.atlassian.net/browse/DMS-696
https://edfi.atlassian.net/browse/DMS-697
https://edfi.atlassian.net/browse/DMS-703
https://edfi.atlassian.net/browse/DMS-704

[DMS-672] Staff Authorization: E2E Test Scenarios

---

eng/docker-compose/setup-keycloak.ps1

[DMS-702] CMS Readonly users realm admin roles restricted

---

.github/workflows/EdFi.Dms.Minimal.Template.PostgreSQL.yml
eng/DatabaseTemplates/DmsManagement.psm1
eng/DatabaseTemplates/Invoke-BuildMinimalTemplate.ps1
eng/DatabaseTemplates/MinimalTemplateSettings.psd1
eng/Package-Management.psm1

Using csproj instead of nuspec to simplify `dotnet pack` calling
Package information is stored in psd1 file
Loaded school years using powershell, because current version of school year loader requires modifying appsettings.json to point to the correct docker containers.
Action successfully executed [here](https://github.com/Ed-Fi-Alliance-OSS/Data-Management-Service/actions/runs/15169122722)

[DMS-688] Minimal Template Build

---

src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore.Tests.Unit/Modules/DiscoveryModuleTests.cs
src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/Content/VersionProvider.cs
src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/EdFi.DataManagementService.Frontend.AspNetCore.csproj
src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/Modules/DiscoveryEndpointModule.cs
src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/General/DiscoveryAPI.feature

[DMS-736] Update Discovery API for 0.6 release

---

eng/CmsHierarchy/ClaimSetFiles/AuthorizationHierarchy.json
eng/CmsHierarchy/ClaimSetFiles/E2E-ExtensionsClaimSet.json
eng/CmsHierarchy/ClaimSetFiles/E2E-NameSpaceBasedClaimSet.json
eng/CmsHierarchy/ClaimSetFiles/E2E-NoFurtherAuthRequiredClaimSet.json
eng/CmsHierarchy/ClaimSetFiles/E2E-RelationshipsWithEdOrgsOnlyClaimSet.json
eng/CmsHierarchy/ClaimSetToAuthHierarchy.cs
eng/CmsHierarchy/Extensions/ClaimExtensions.cs
eng/CmsHierarchy/Model/ClaimSet.cs
eng/CmsHierarchy/Program.cs
eng/CmsHierarchy/Properties/launchSettings.json
eng/CmsHierarchy/README.md
src/config/backend/EdFi.DmsConfigurationService.Backend.Postgresql/Deploy/Scripts/0011_Insert_ClaimsHierarchy.sql

[DMS-737] Add missing extension claims

---

eng/docker-compose/.env.e2e
eng/docker-compose/.env.example
eng/docker-compose/README.md
src/Directory.Packages.props
src/dms/clis/EdFi.DataManagementService.ApiSchemaDownloader.Tests.Integration/ApiSchemaDownloaderTests.cs
src/dms/clis/EdFi.DataManagementService.ApiSchemaDownloader/Properties/launchSettings.json
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ArrayUniquenessValidationMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/CoerceDateFormatMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/CoerceDateTimesMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/CoerceFromStringsMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ParsePathMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ReferenceArrayUniquenessValidationMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ResourceActionAuthorizationMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateDecimalMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateDocumentMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateEndpointMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateEqualityConstraintMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateMatchingDocumentUuidsMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/Middleware/ValidateQueryMiddlewareTests.cs
src/dms/core/EdFi.DataManagementService.Core/ApiSchema/ApiSchemaDocuments.cs
src/dms/core/EdFi.DataManagementService.Core/ApiSchema/Model/ProjectEndpointName.cs
src/dms/core/EdFi.DataManagementService.Core/ApiSchema/ProjectSchema.cs
src/dms/core/EdFi.DataManagementService.Core/Middleware/ParsePathMiddleware.cs
src/dms/core/EdFi.DataManagementService.Core/Middleware/ResourceActionAuthorizationMiddleware.cs
src/dms/core/EdFi.DataManagementService.Core/Middleware/ValidateEndpointMiddleware.cs
src/dms/core/EdFi.DataManagementService.Core/Model/No.cs
src/dms/core/EdFi.DataManagementService.Core/Model/PathComponents.cs
src/dms/tests/EdFi.DataManagementService.Tests.E2E/Features/General/XSDMetadata.feature

- **APISchema version bump** for kebab-casing enforcement of projectEndpointName
- **Rename ApiSchema ProjectNamespace to ProjectEndpointName** No logic change, renamed for clarity

[DMS-740] Refactor projectEndpointName for kebab-casing change

---

src/dms/core/EdFi.DataManagementService.Core.Tests.Unit/ApiServiceJwtAuthenticationTests.cs
src/dms/core/EdFi.DataManagementService.Core/ApiService.cs
src/dms/core/EdFi.DataManagementService.Core/DmsCoreServiceExtensions.cs
src/dms/core/EdFi.DataManagementService.Core/Middleware/ProvideAuthorizationFiltersMiddleware.cs
src/dms/core/EdFi.DataManagementService.Core/Middleware/RequestResponseLoggingMiddleware.cs
src/dms/core/EdFi.DataManagementService.Core/Middleware/ResourceActionAuthorizationMiddleware.cs
src/dms/core/EdFi.DataManagementService.Core/Utilities/LoggingSanitizer.cs
src/dms/frontend/EdFi.DataManagementService.Frontend.AspNetCore/Infrastructure/LoggingMiddleware.cs

- **Logging enhancements**
- **Move await statement outside try catch**

[DMS-817] Improve logging and traceability
